### ISSUE TITLE
Unable to find service in HTTPProxy with more than one route

### ISSUE THREAD

**Issue by mvgmb** [argoproj-labs/rollouts-plugin-trafficrouter-contour#15]
**Describe the bug**

When trying to set the weight of an HTTPProxy with more than one route, it is only able to find the services of the first route:

```
'TrafficRoutingError' failed to set weight via plugin: the service: api-canary is not found in HTTPProxy
```

**To Reproduce**

Create an HTTPProxy with more than one route, and try to set the weight of the second route.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app
spec:
  virtualhost:
    fqdn: example.com
    tls:
      secretName: ingress
  routes:
    - conditions:
        - prefix: /
      services:
        - name: web
          port: 80
        - name: web-canary
          port: 80
    - conditions:
        - prefix: /api
      services:
        - name: api
          port: 80
        - name: api-canary
          port: 80
```

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
spec:
  strategy:
    canary:
      canaryService: api-canary
      stableService: api
      trafficRouting:
        plugins:
          argoproj-labs/contour:
            namespace: api
            httpProxy: api
```

**Version**
```
argoproj/argo-rollouts:v1.5.0
argoproj-labs/rollouts-plugin-trafficrouter-contour:v0.1.1
```
