### ISSUE TITLE
Handle multiple HTTPProxies

### ISSUE THREAD

**Issue by sneako** [argoproj-labs/rollouts-plugin-trafficrouter-contour#19]
# Summary

Handle multiple HTTPProxies

# Motivation

We run contour with many HTTPProxies pointed at a single service. If we were to use this plugin in the current state, it would only adjust the weight of one HTTPProxy, leaving 100 weight on the rest of them.

# Proposal

Instead of:
```
trafficRouting:
  plugins:
    argoproj-labs/contour:
      httpProxy: my-proxy
```
Configuration could look like:
```
trafficRouting:
  plugins:
    argoproj-labs/contour:
      httpProxies:
        - my-proxy
        - my-other-proxy
```

Then we can simply loop over this list of proxies.
