### ISSUE TITLE
How to update weight when HttpProxy has mutil services

### ISSUE THREAD

**Issue by yyzxw** [argoproj-labs/rollouts-plugin-trafficrouter-contour#52]
# Summary

when HttpProxy routes has mutil services, how to update service weight to make sure canary & stable service a determined proportion of traffic is assigned.

# Motivation

httpProxy:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: demo
spec:
  routes:
    - conditions:
        - header:
            name: ':method'
            regex: POST|DELETE|PUT|PATCH|OPTIONS|HEAD
          prefix: /user
      services:
        - name: stable-service
          port: 80
          weight: 10
        - name: canary-service
          port: 80
          weight: 90
        - name: other-service
          port: 80
          weight: 10  
``` 

when update stable & canary service weight, how to update `other-service` weight?

# Proposal

maybe delete `other-service` or set `other-service` wight to 0 is a reasonable way.

or someone has some good idea?
