### ISSUE TITLE
Set weight failed when HttpProxy has multi routes

### ISSUE THREAD

**Issue by zengchongliner** [argoproj-labs/rollouts-plugin-trafficrouter-contour#62]
**Describe the bug**
Set weight failed when HttpProxy has multi routes.
This is a part of HTTPProxy of conditions.
```yaml
spec:
  ingressClassName: gateway-zeng-up
  routes:
    - conditions:
        - header:
            name: ':method'
            regex: GET|POST|DELETE|PUT|PATCH|OPTIONS|HEAD
          prefix: /
        - header:
            exact: eureka
            name: route
      jwtVerificationPolicy: {}
      loadBalancerPolicy:
        strategy: RoundRobin
      rateLimitPolicy: {}
      services:
        - name: sesame-b5cde76a93-sesame
          port: 30902
          weight: 100
    - conditions:
        - header:
            name: ':method'
            regex: GET|POST|DELETE|PUT|PATCH|OPTIONS|HEAD
          prefix: /
      jwtVerificationPolicy: {}
      loadBalancerPolicy:
        strategy: RoundRobin
      rateLimitPolicy: {}
      services:
        - name: rollouts-demo
          port: 8080
          weight: 100
        - name: rollouts-demo-canary
          port: 8080
```
**Logs**
```
time="2024-01-23T06:44:58Z" level=error msg="rollout syncHandler error: failed to set weight via plugin: failed to create patch : the total weight must equals to 100" namespace=skoala-zeng rollout=rollouts-demo
time="2024-01-23T06:44:58Z" level=info msg="rollout syncHandler queue retries: 258 : key \"skoala-zeng/rollouts-demo\"" namespace=skoala-zeng rollout=rollouts-demo
time="2024-01-23T06:44:58Z" level=error msg="failed to set weight via plugin: failed to create patch : the total weight must equals to 100\n" error="<nil>"
```
